on: push
permissions: write-all
jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: image edit

        steps:
        - name: Checkout source repo
          uses: actions/checkout@v2
          with:
            path: ./dh-vaultwarden

        - name: Checkout kustomize repo
          uses: actions/checkout@v2
          with: 
            repository: "${{ github.repository_owner }}/kustomize"
            token: ${{ secrets.ACTIONS_TOKEN }}
            path: ./kustomize

        - name: Replace image 
          run: |
             echo "images: \n\v- name: vaultwarden \n\vvewName: sohag/vaultwarden \n\vnewTag: sohag/vaultwarden:${{github.ref_name}}-${GITHUB_SHA::7}" >> ./kustomize/vault/kustomization.yaml
        - name: "commander"
          run: ls -lA ./kustomize; cat ./kustomize/vault/deployment.yaml
        - name: "save hello"
          run: |
            cd ./kustomize
            git config --local user.name "${{ github.repository_owner }}"
            git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
            git add vault/deployment.yaml
            git commit -m "image edit and push"
            git status

        - name: "check config"
          run: |
            cd ./kustomize
            git config -l
        - name: "push you"
          run: |
            cd ./kustomize
            git push origin main

