on: push

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout source repo
          uses: actions/checkout@v2
          with:
            path: ./dh-vaultwarden

        - name: Checkout config-kustomize
          uses: actions/checkout@master
          with: 
            repository: tomassirio/projectB
            token: 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 #${{ secrets.ACTIONS_TOKEN }}
            path: ./kustomize

        - name: Copy/Create file
          run: |

            echo "images: \n\v- name: vaultwarden \n\vvewName: sohag/vaultwarden \n\vnewTag: sohag/vaultwarden:${GITHUB_SHA::7}" >> ./kustomize/vault/deployment.yaml

        - name: Push Project B
          run: |
            cd ./kustomize
            git add .
            git config user.name sohag033
            git config user.email sohag033@gmail.com
            git commit -am "File push to kustomize"
            git push
