on: push
permissions: write-all
jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout source repo
          uses: actions/checkout@v2
          with:
            path: ./dh-vaultwarden

        - name: Checkout kustomize repo
          uses: actions/checkout@v3
          with: 
            repository: sohag033/kustomize
            token: ${{ secrets.GITHUB_TOKEN }}
            path: ./kustomize
#           env:
#               AGITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

        - name: Copy/Create file
          run: |
             echo ${{ secrets.ACTIONS_TOKEN }}
             echo $ACTIONS_TOKEN
             echo "images: \n\v- name: vaultwarden \n\vvewName: sohag/vaultwarden \n\vnewTag: sohag/vaultwarden:${{github.ref_name}}-${GITHUB_SHA::7}" >> kustomize/vault/deployment.yaml
             cd ./kustomize
             git add .
             git config user.name sohag033
             git config user.email  sohag033@gmail.com
             git commit -am "image edit and push"
             git push https://${{ secrets.ACTIONS_TOKEN }}@github.com/sohag033/kustomize.git
#   Jhust test
#         - name: Push changes
#           run: |
#               cd ./kustomize
#               git add .
#               git config user.name github-actions
#               git config user.email  github-actions@github.com
#               git commit -am "image edit and push"
#               git push
