on: push

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout source repo
          uses: actions/checkout@v2
          with:
            path: ./dh-vaultwarden

        - name: Checkout kustomize repo
          uses: actions/checkout@main
          with: 
            repository: sohag033/kustomize
            token: ${{ secrets.GITHUB_TOKEN }}
            path: ./kustomize

        - name: Copy/Create file
          run: |
             echo "images: \n\v- name: vaultwarden \n\vvewName: sohag/vaultwarden \n\vnewTag: sohag/vaultwarden:${GITHUB_SHA::7}" >> kustomize/vault/deployment.yaml

        - name: Push Project   
          run: |
            cd ./kustomize
            git add .
            git config user.name sohag033
            git config user.email  sohag033@gmail.com
            git commit -am "image edit and push"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/sohag033/kustomize.git
