# Store the personal access token, Docker Hub username and password as GitHub secrets.
name: 'CI'

on:
  push:
    branches:
      - main
#     - feature/*
#   # Triggers the workflow when a PR created against main branch has been closed
#   pull_request:
#     branches:
#     - main
#     types: [closed]

# env:
#   IMAGE_NAME: sohag/vaultwarden

jobs:

#   buildAndPush:
#     name: 'Build and Push a Docker Image'
#     runs-on: ubuntu-latest

#     # Uses the Bash shell regardless of the GitHub Actions runner
#     defaults:
#       run:
#         shell: bash
    
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Docker build
#       run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_SHA::7}
    

#     - name: Login to the registry
#       uses: docker/login-action@v1 
#       with:
#         username: sohag # ${{ secrets.DOCKERHUB_USERNAME }}
#         password: 723384e0-aa1a-47fb-b879-816348fabe36 # ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Docker push
#       run: docker push $IMAGE_NAME:${GITHUB_SHA::7}

  UpdateTheVersion:
#     needs: buildAndPush
    name: 'Update Docker image version'
    runs-on: ubuntu-latest
    # Runs only when the PR has been merged
#     if: github.event.pull_request.merged

#     defaults:
#       run:
#         shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Updates the image version in the deployment manifest
    - name: Update the version
      run: |
        git clone https://github.com/sohag033/kustomize.git
        cd kustomize
        echo "images: \n\v- name: vaultwarden \n\vvewName: sohag/vaultwarden \n\vnewTag: sohag/vaultwarden:${GITHUB_SHA::7}" >> vault/deployment.yaml
        git add . 
        git commit -m "Updated the version of the Docker image and push"  
        git config --global user.name "sohag033"
        git config --global user.email "sohag033@gmail.com"
        git push https://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@github.com/sohag033/kustomize.git 
        sleep 10s; cd .. 
        rm -rf kustomize

    # Commits the change
    - name: Commit files 
      run: |
        git config --local user.email "sohag033@gmail.com"
        git config --local user.name "sohag"
        git status
        git add .
        git commit -m "Updated the version of the Docker image from kustmiz and delete"
    # Pushes the updated file to the repo
    - name: Push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        force: true
