on: push

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout source repo
          uses: actions/checkout@v2
          with:
            path: ./dh-vaultwarden
            token: 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

        - name: Checkout kustomize repo
          uses: actions/checkout@master
          with: 
            repository: sohag033/kustomize
            token: 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 #${{ secrets.ACTIONS_TOKEN }}
            path: ./kustomize
#           env:
#               AGITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

        - name: Copy/Create file
          run: |
             echo "images: \n\v- name: vaultwarden \n\vvewName: sohag/vaultwarden \n\vnewTag: sohag/vaultwarden:${GITHUB_SHA::7}" >> kustomize/vault/deployment.yaml
             #cd ./kustomize
             #git add .
             #git config user.name sohag033
             #git config user.email  sohag033@gmail.com
             #git commit -am "image edit and push"
             #git push https://${{ secrets.GITHUB_TOKEN }}@github.com/sohag033/kustomize.git
           #need to resolve
        - name: Push changes
          run: |
              cd ./kustomize
              git add .
              git config user.name sohag033
              git config user.email  sohag033@gmail.com
              git commit -am "image edit and push"
              git push
#         - name: Push Project   
#           run: |
#             cd ./kustomize
#             git add .
#             git config user.name sohag033
#             git config user.email  sohag033@gmail.com
#             git commit -am "image edit and push"
#             git push 
