  name: 'CI'

  on:
   push:
     branches:
      - 'main'
      - 'staging'
      - feature/*
  # Triggers the workflow when a PR created against main branch has been closed
#    pull_request:
#         branches:
#          - main
#         types: [closed]
  jobs:
       replicate-file:
        runs-on: ubuntu-latest
        name: image edit

        steps:
        - name: Checkout source repo
          uses: actions/checkout@v2
          with:
            path: ./dh-vaultwarden

        - name: Checkout kustomize repo
          uses: actions/checkout@v2
          with: 
            repository: "${{ github.repository_owner }}/kustomize"
            token: ${{ secrets.ACTIONS_TOKEN }}
            path: ./kustomize

        - name: Replace image-prod 
          if: github.ref == 'refs/heads/main'
          run: |
             sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
             sudo add-apt-repository ppa:rmescandon/yq
             sudo apt update
             sudo apt install yq -y
             yq --version
             source <(yq shell-completion bash)
             cd ./kustomize/overlays/prod
             yq e -i '.images[0].newTag = "${{github.ref_name}} - ${{github.sha}}"' 'kustomization.yaml'
             git config --local user.name "${{ github.repository_owner }}"
             git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
             git add .
             git commit -m "image edit and push"
             git status
            
        - name: Replace image-stg
          if: github.ref == 'refs/heads/staging'
          run: |
              cd ./kustomize/overlays/stg
              yq e -i '.images[0].newTag = "${{github.ref_name}} - ${{github.sha}}"' 'kustomization.yaml'
              git config --local user.name "${{ github.repository_owner }}"
              git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
              git add .
              git commit -m "image edit and push"
              git status
             
        - name: "commander"
          run: ls -lA ./kustomize; cat ./kustomize/overlays/prod/kustomization.yaml
#         - name: "save image name"
#           run: |
#             cd ./kustomize
#             git config --local user.name "${{ github.repository_owner }}"
#             git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
#             git add .
#             git commit -m "image edit and push"
#             git status

        - name: "check config"
          run: |
            cd ./kustomize
            git config -l
        - name: "push you"
          run: |
            cd ./kustomize
            git push origin main

