name: Vault-warden Docker Image build and push to docker.io

on:
  push:
    branches: 
      - main
      - staging
    
  #pull_request:
    #branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
         image: vault-warden/{{}}
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
