
on:
  push:
    branches: 
      - main
      - staging
    
  #pull_request:
    #branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
#     - name: Docker build
#       run: |
#        docker build . -t vaultwarden:${{ github.sha }}
       
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with: # how to set secrets in github https://docs.github.com/en/actions/security-guides/encrypted-secrets
        username: sohag # replace with secrets username: ${{ secrets.DOCKER_USERNAME }}
        password: 3332221110  # replace with secrets password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sohag/vaultwarden:${{ github.sha }},sohag/vaultwarden:$GITHUB_REF_NAME 
        build-args: |
           version=${{ github.sha }}

